### ISSUE TITLE
Загрузчик с XIP-режимом

### ISSUE THREAD

**Issue by spam-receiver** [Elron-tech/elbear_fw_bootloader#4]
Чтобы программа загрузки могла прошивать код через SPIFI, микросхему флеш-памяти требуется выводить из режима XIP или сбрасывать полностью. Для этого обновите программу из моего репозитория: [mik32-uploader](https://github.com/spam-receiver/mik32-uploader)

Также я регулярно дорабатываю и обновляю демонстрационный пример своего начального загрузчика: [EEPROM_to_SPIFI](https://github.com/spam-receiver/mik32-examples/tree/main/HAL_EEPROM_to_SPIFI), но он требует обновления библиотек [mik32-hal](https://github.com/spam-receiver/mik32-hal) и [mik32v2-shared](https://github.com/spam-receiver/mik32v2-shared).

**Comment by khristolyubov** [comment]
Спасибо! Обязательно протестируем эти изменения и скорее всего добавим их в основную ветку. Судя по описанию они обеспечивают хороший прирост производительности.

**Comment by spam-receiver** [comment]
> Судя по описанию они обеспечивают хороший прирост производительности.

Я постараюсь дополнить ваш код так, что он будет автоматически определять рабочий режим SPIFI с максимальной производительностью, вне зависимости от модели микросхемы внешней флеш-памяти.

**Comment by spam-receiver** [comment]
Дополнил загрузчик режимом QPI. Выбирается константой CHIP_MODE: 0 = QSPI, 1 = QPI.
Естественно без повторяющейся команды чтения, то есть в той же XIP модификации. Быстрее некуда!

**Comment by khristolyubov** [comment]
На платах elbear стоят микросхемы памяти без поддержки режима qpi. Видел Ваше сообщение на форуме, что на 16 МБ версии режим таки завелся. Это странно и очень круто! К сожалению, смогу проверить на наших платах не раньше чем через неделю.

**Comment by spam-receiver** [comment]
> ... на 16 МБ версии режим таки завелся. Это странно и очень круто!

Ничего странного. Маркировка на корпусе микросхемы «25Q128JVSM» является сокращением от «W25Q128JVSIM», что означает W25Q128JV-DTR в корпусе SOIC-8 208-mil. Она не только поддерживает режим QPI, но ещё и умеет работать на полупериодах тактового сигнала, то есть в два раза быстрее. Жаль что это не поддерживается блоком SPIFI MIK32.
